'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getCurrentUser, getOrders, getProducts, money, saveOrders, saveProducts } from '../../components/storage';

const blank={title:'',category:'Fashion',price:'',image:'',description:'',stock:'',featured:false,bestSeller:false};
export default function AdminPage(){
 const [checking,setChecking]=useState(true); const [user,setUser]=useState(null);
 const [products,setProducts]=useState([]); const [orders,setOrders]=useState([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState(null);
 useEffect(()=>{ const current=getCurrentUser(); setUser(current); setChecking(false); if(current?.role==='admin'){setProducts(getProducts()); setOrders(getOrders())}},[]);
 if(checking) return <main className="section"><p className="empty">Checking access...</p></main>;
 if(!user) return <main className="section accessBox"><h1>Нэвтрэх шаардлагатай</h1><p className="muted">Admin dashboard руу орохын тулд admin эрхтэй account-аар нэвтэрнэ үү.</p><Link className="btn" href="/login">Login</Link></main>;
 if(user.role!=='admin') return <main className="section accessBox"><h1>Admin эрх шаардлагатай</h1><p className="muted">Таны account одоогоор <b>{user.role}</b> төлөвтэй байна. Admin хэсэг зөвхөн admin хэрэглэгчид харагдана.</p><Link className="btn" href="/products">Products руу буцах</Link></main>;
 const persistProducts=next=>{setProducts(next); saveProducts(next)}; const persistOrders=next=>{setOrders(next); saveOrders(next)};
 const submit=e=>{e.preventDefault(); const payload={...form, id:editing||'p'+Date.now(), price:Number(form.price), stock:Number(form.stock)}; persistProducts(editing?products.map(p=>p.id===editing?payload:p):[payload,...products]); setForm(blank); setEditing(null);};
 const edit=p=>{setEditing(p.id); setForm(p)};
 return <main className="section admin"><div className="adminHero"><div><p className="eyebrow">Admin panel</p><h1>Admin dashboard</h1><p className="muted">Logged in as {user.name} · {user.role}</p></div><span className="roleBadge">{user.role}</span></div><section className="panel"><h2>{editing?'Edit product':'Add product'}</h2><form className="adminForm" onSubmit={submit}><input required placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input required type="number" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input required placeholder="Image URL" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><input required type="number" placeholder="Stock" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><textarea required placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={form.bestSeller} onChange={e=>setForm({...form,bestSeller:e.target.checked})}/> Best seller</label><button className="btn">Save product</button></form></section><section><h2>Products</h2><div className="adminList">{products.map(p=><article className="adminRow" key={p.id}><span>{p.title}</span><b>{money(p.price)}</b><button onClick={()=>edit(p)}>Edit</button><button className="danger" onClick={()=>persistProducts(products.filter(x=>x.id!==p.id))}>Delete</button></article>)}</div></section><section><h2>Orders</h2><div className="adminList">{orders.length===0&&<p className="empty">No orders yet.</p>}{orders.map(o=><article className="adminRow order" key={o.id}><div><b>{o.id}</b><p>{o.customer.name} · {o.customer.phone} · {money(o.total)}</p></div><select value={o.status} onChange={e=>persistOrders(orders.map(x=>x.id===o.id?{...x,status:e.target.value}:x))}><option>Pending</option><option>Paid</option><option>Processing</option><option>Shipped</option><option>Completed</option><option>Cancelled</option></select></article>)}</div></section></main>
}
